import { Project } from "./types";

export const projects: Project[] = [
  {
    id: 1,
    title: "AI Legal Assistant",
    description:
      "Автоматизация юридических задач – ИИ помощник, судебная практика, CRM для юристов",
    status: "active",
    productManager: "@titov.artur",
    teamLeader: "@elena.romanova",
    team: ["@ildar.shaikhutdinov", "@pavel.gordienko"],
    teamLeaderBack: "@dmitry.kvitkovsky",
    backLanguage: "Python",
    projectManager: "@veronika.soshenko",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    progressFront: 100,
    progressBackend: 100,
    details:
      "Юридическая платформа для автоматизации рутинных задач: база судебной практики, шаблоны документов, юридический справочник, CRM для юристов и AI-консультант. Оптимизируйте работу с документами и клиентами!",
    repository: "https://github.com/AVB-Invest/AI_Legal_Assistant",
    figmaUrl:
      "https://www.figma.com/design/a1Cqijskoqo0YVguZo3O5b/Verdictor?node-id=10199-73957&p=f&t=OcarOBfRbVJSVRFC-0",
    chat: "https://chat.avbinvest.co/legal-5d-platform/channels/ai-legal-assistant-frontend",
    boards: "",
    meetingTime: "Четверг в 19:00",
    meetingUrl: "https://meet.google.com/zdw-wnkq-ivm?authuser=0",
  },
  {
    id: 2,
    title: "AI Legal Assistant",
    description:
      "Автоматизация юридических задач – ИИ помощник, судебная практика, CRM для юристов",
    status: "active",
    productManager: "@titov.artur",
    teamLeader: "@elena.romanova",
    team: ["@ildar.shaikhutdinov", "@pavel.gordienko"],
    teamLeaderBack: "@dmitry.kvitkovsky",
    backLanguage: "Python",
    projectManager: "@veronika.soshenko",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    progressFront: 100,
    progressBackend: 100,
    details:
      "Юридическая платформа для автоматизации рутинных задач: база судебной практики, шаблоны документов, юридический справочник, CRM для юристов и AI-консультант. Оптимизируйте работу с документами и клиентами!",
    repository: "https://github.com/AVB-Invest/AI_Legal_Assistant",
    figmaUrl:
      "https://www.figma.com/design/a1Cqijskoqo0YVguZo3O5b/Verdictor?node-id=10199-73957&p=f&t=OcarOBfRbVJSVRFC-0",
    chat: "https://chat.avbinvest.co/legal-5d-platform/channels/ai-legal-assistant-frontend",
    boards: "",
    meetingTime: "Четверг в 19:00",
    meetingUrl: "https://meet.google.com/zdw-wnkq-ivm?authuser=0",
  },
  {
    id: 3,
    title: "AI Legal Assistant",
    description:
      "Автоматизация юридических задач – ИИ помощник, судебная практика, CRM для юристов",
    status: "active",
    productManager: "@titov.artur",
    teamLeader: "@elena.romanova",
    team: ["@ildar.shaikhutdinov", "@pavel.gordienko"],
    teamLeaderBack: "@dmitry.kvitkovsky",
    backLanguage: "Python",
    projectManager: "@veronika.soshenko",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    progressFront: 100,
    progressBackend: 100,
    details:
      "Юридическая платформа для автоматизации рутинных задач: база судебной практики, шаблоны документов, юридический справочник, CRM для юристов и AI-консультант. Оптимизируйте работу с документами и клиентами!",
    repository: "https://github.com/AVB-Invest/AI_Legal_Assistant",
    figmaUrl:
      "https://www.figma.com/design/a1Cqijskoqo0YVguZo3O5b/Verdictor?node-id=10199-73957&p=f&t=OcarOBfRbVJSVRFC-0",
    chat: "https://chat.avbinvest.co/legal-5d-platform/channels/ai-legal-assistant-frontend",
    boards: "",
    meetingTime: "Четверг в 19:00",
    meetingUrl: "https://meet.google.com/zdw-wnkq-ivm?authuser=0",
  },
  {
    id: 4,
    title: "AI Legal Assistant",
    description:
      "Автоматизация юридических задач – ИИ помощник, судебная практика, CRM для юристов",
    status: "active",
    productManager: "@titov.artur",
    teamLeader: "@elena.romanova",
    team: ["@ildar.shaikhutdinov", "@pavel.gordienko"],
    teamLeaderBack: "@dmitry.kvitkovsky",
    backLanguage: "Python",
    projectManager: "@veronika.soshenko",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    progressFront: 100,
    progressBackend: 100,
    details:
      "Юридическая платформа для автоматизации рутинных задач: база судебной практики, шаблоны документов, юридический справочник, CRM для юристов и AI-консультант. Оптимизируйте работу с документами и клиентами!",
    repository: "https://github.com/AVB-Invest/AI_Legal_Assistant",
    figmaUrl:
      "https://www.figma.com/design/a1Cqijskoqo0YVguZo3O5b/Verdictor?node-id=10199-73957&p=f&t=OcarOBfRbVJSVRFC-0",
    chat: "https://chat.avbinvest.co/legal-5d-platform/channels/ai-legal-assistant-frontend",
    boards: "",
    meetingTime: "Четверг в 19:00",
    meetingUrl: "https://meet.google.com/zdw-wnkq-ivm?authuser=0",
  },
  {
    id: 5,
    title: "AI Legal Assistant",
    description:
      "Автоматизация юридических задач – ИИ помощник, судебная практика, CRM для юристов",
    status: "active",
    productManager: "@titov.artur",
    teamLeader: "@elena.romanova",
    team: ["@ildar.shaikhutdinov", "@pavel.gordienko"],
    teamLeaderBack: "@dmitry.kvitkovsky",
    backLanguage: "Python",
    projectManager: "@veronika.soshenko",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    progressFront: 100,
    progressBackend: 100,
    details:
      "Юридическая платформа для автоматизации рутинных задач: база судебной практики, шаблоны документов, юридический справочник, CRM для юристов и AI-консультант. Оптимизируйте работу с документами и клиентами!",
    repository: "https://github.com/AVB-Invest/AI_Legal_Assistant",
    figmaUrl:
      "https://www.figma.com/design/a1Cqijskoqo0YVguZo3O5b/Verdictor?node-id=10199-73957&p=f&t=OcarOBfRbVJSVRFC-0",
    chat: "https://chat.avbinvest.co/legal-5d-platform/channels/ai-legal-assistant-frontend",
    boards: "",
    meetingTime: "Четверг в 19:00",
    meetingUrl: "https://meet.google.com/zdw-wnkq-ivm?authuser=0",
  },
  {
    id: 6,
    title: "AI Legal Assistant",
    description:
      "Автоматизация юридических задач – ИИ помощник, судебная практика, CRM для юристов",
    status: "active",
    productManager: "@titov.artur",
    teamLeader: "@elena.romanova",
    team: ["@ildar.shaikhutdinov", "@pavel.gordienko"],
    teamLeaderBack: "@dmitry.kvitkovsky",
    backLanguage: "Python",
    projectManager: "@veronika.soshenko",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    progressFront: 100,
    progressBackend: 100,
    details:
      "Юридическая платформа для автоматизации рутинных задач: база судебной практики, шаблоны документов, юридический справочник, CRM для юристов и AI-консультант. Оптимизируйте работу с документами и клиентами!",
    repository: "https://github.com/AVB-Invest/AI_Legal_Assistant",
    figmaUrl:
      "https://www.figma.com/design/a1Cqijskoqo0YVguZo3O5b/Verdictor?node-id=10199-73957&p=f&t=OcarOBfRbVJSVRFC-0",
    chat: "https://chat.avbinvest.co/legal-5d-platform/channels/ai-legal-assistant-frontend",
    boards: "",
    meetingTime: "Четверг в 19:00",
    meetingUrl: "https://meet.google.com/zdw-wnkq-ivm?authuser=0",
  },
];
